apiVersion: v1
data:
  v1.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        location / {
            return 200 "hostname is $hostname\n App version is v1\n";
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-v1
